/**
 * Created by tom on 07/08/15.
 */

module.exports = {
    CONFIG_SERVER_ADDRESS: "localhost",
    CONFIG_SERVER_PORT: "9000",

    DEFAULT_SIZE: 10,
    DEFAULT_POSITION_X: 0,
    DEFAULT_POSITION_Y: 0,

    PLAYER_POSITION_CHANGED: "PLAYER_POSITION_CHANGED",
    PLAYER_STARTING_STATE: "PLAYER_STARTING_STATE",
    PLAYER_ACTIVE_PLAYERS: "PLAYER_ACTIVE_PLAYERS"
};