/**
 * Created by tom on 07/08/15.
 */

module.exports = {
    CONFIG_SERVER_ADDRESS: "localhost",
    CONFIG_SERVER_PORT: "9000",
    CONFIG_SERVER_TICK_RATE: 60,

    DEFAULT_SIZE: 10,
    DEFAULT_POSITION_X: 0,
    DEFAULT_POSITION_Y: 0,

    EVENT_PLAYER_POSITION_CHANGED: "EVENT_PLAYER_POSITION_CHANGED",
    EVENT_PLAYER_JOINED: "EVENT_PLAYER_JOINED",
    EVENT_PLAYER_LEFT: "EVENT_PLAYER_LEFT",
    EVENT_FOOD_ADDED: "EVENT_FOOD_ADDED",
    EVENT_FOOD_EATEN: "EVENT_FOOD_EATEN",

    PLAYER_POSITION_CHANGED: "PLAYER_POSITION_CHANGED",
    PLAYER_STARTING_STATE: "PLAYER_STARTING_STATE",
    PLAYER_ACTIVE_PLAYERS: "PLAYER_ACTIVE_PLAYERS"
};